Algoritmo "INTEIRO"

Var

   n1, n2, n3 : inteiro

Inicio

      escreva("Digite o primeiro número: ")
      leia(n1)
      escreva("Digite o segundo número: ")
      leia(n2)
      escreva("Digite o terceiro número: ")
      leia(n3)
      
      se (n1>n2) e (n1>n3) entao
      escreva(n1)
      senao
      se (n2>n3) e (n2>n1) entao
      escreva(n2)
      senao
      se (n3>n2) e (n3>n1) entao
      escreva(n3)
      fimse
      fimse
      fimse

Fimalgoritmo